version: '3.4'
services:
  postgres:
    image: "postgres:15.2"
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
  app:
    image: budget_app:latest
    entrypoint: "/app/docker-entrypoint.sh"
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/rails
      - ruby-bundle-cache:/bundle
  replay-backup:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.db
    depends_on:
      - 'postgres'
    # volumes:
      # - /mnt/sdb/db_backups:/db_backups
volumes:
  ruby-bundle-cache:
    external: true