#
default: &default
  encoding: unicode
  adapter:  postgresql
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_app_development

test:
  <<: *default
  database: budget_app_test

production:
  <<: *default
  database: budget_app_production
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>
